name: 'calver-release-action'
description: 'GitHub Action to generate Calver release'
author: 'cho0o0'
inputs:
  api_token:
    required: true
    description: 'GitHub token to be used for this action'
  dry_run:
    required: false
    default: 'false'
    description: 'Whether to publish a release or just print supposed version'
  generate_release_notes:
    required: false
    default: 'true'
    description: 'Whether to generate release notes'
  timezone:
    required: false
    default: 'utc'
    description: 'Timezone to be used for version generations'
  target_commitish:
    required: false
    description: 'Target commitish to be used for release. The default value is SHA of current workflow context.'
  release_title:
    required: false
    default: 'Release ver. ${version}'
    description: 'Title format for the release. ${version} can be used and replaced as the generated version string.'
outputs:
  version:
    description: 'Generated string of new version'
  url:
    description: 'GitHub url for the published release'
  title:
    description: 'Generated string of the release title'
runs:
  using: node16
  main: 'dist/index.js'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
